services:
  postgresql-keycloak:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresql-keycloak-username
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgresql-keycloak
    volumes:
      - postgresql-keycloak:/var/lib/postgresql-keycloak/data

  keycloak:
    command: start-dev
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HOSTNAME: localhost
      KC_DB_URL_PROPERTIES: '?ssl=disable'
      KC_DB_URL_HOST: postgresql-keycloak
      KC_DB_URL_DATABASE: postgresql-keycloak
      KC_DB_USERNAME: postgresql-keycloak-username
      KC_DB_PASSWORD: password
      KC_DB: postgres
    depends_on:
      - postgresql-keycloak

  postgresql-users-server:
    image: postgres:16
    hostname: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: users-server
      POSTGRES_USER: users-server-username
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql-users-server:/var/lib/postgresql-geospatial-server/data

volumes:
  postgresql-keycloak: { }
  postgresql-users-server: { }