spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.server-url}/realms/${app.keycloak.user-realm.name}
          jwk-set-uri: ${app.keycloak.server-url}/realms/${app.keycloak.user-realm.name}/protocol/openid-connect/certs
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/users-server}
    username: ${SPRING_DATASOURCE_USERNAME:users-server-username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    jpa:
      generate-ddl: false
      show-sql: true
      properties:
        hibernate:
          ddl-auto: validate
    flyway:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/users-server}
      username: ${SPRING_DATASOURCE_USERNAME:users-server-username}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
      baseline-on-migration: true
      enabled: true
      locations: classpath:db/migration

server:
  port: {SERVER_PORT:8080}

app:
  keycloak:
    admin:
      client-id:  ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
      realm: ${KEYCLOAK_ADMIN_REALM:master}
    user-realm:
      name: ${KEYCLOAK_REALM:geogreen}
      client-id: user-client

    server-url: ${KEYCLOAK_URL:http://217.198.13.249:30096}
    mail:
      verification-time: 10

logging:
  level:
    root: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true